services:
  postgres:
    container_name: postgres-sql-ims
    image: postgres:15
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: cv_application
    volumes:
      - postgres:/data/postgres
    networks:
      - spring-demo
    restart: unless-stopped
    ports:
      - 5432:5432

  mail-dev:
    container_name: mail-dev-ims
    image: maildev/maildev
    ports:
      - 1080:1080
      - 1025:1025
  keycloak:
    container_name: keycloak-ims
    image: quay.io/keycloak/keycloak:26.3.3
    ports:
      - 9090:8080
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    networks:
      - spring-demo
    command:
      - "start-dev"

networks:
  spring-demo:
    driver: bridge

volumes:
  postgres:
    driver: local
